services:
    SystemCtl\:
        autowire: true
        resource: '../../'

    SystemCtl\Action\:
        public: true
        resource: '../../Action'
        tags: ['action']

    SystemCtl\Container\ActionContainer:
        arguments: [!tagged action]