services:
    SystemCtl\:
        public: true
        resource: '../../SystemCtl'

    SystemCtl\Action\:
        resource: '../../SystemCtl/Action'
        tags: ['action']

    SystemCtl\Container\ActionContainer:
        arguments: [!tagged action]